name: CI

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: show dir
        run: ls -la
      - name: change dir
        run: cd app
      - uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: install angular cli
        run: |
          cd app
          npm install -g @angular/cli
      - name: build
        run: |
          cd app
          npm install
          ng build


