name: GitHub-Actions
env:
  App_Name    : "Angular"
  Package_Name: "version-${{ github.sha }}"

on: 
  push:
    branches:
    - main
jobs:
  CI:
    runs-on: self-hosted
    
    steps:
            - name: run
              run: ls
      
      

