name: GitHub-Actions
env:
  App_Name    : "Angular"
  Package_Name: "version-${{ github.sha }}"

on: 
  push:
    branches:
    - main
jobs:
  CI:
    runs-on: ubuntu-20.04
    
    steps:
            - name: clone
              uses: actions/checkout@v1
            - name: List folder
              run : ls -la
      
      

