name: CI

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: show dir
        run: ls -la
      - name: change dir
        run: cd app
      - uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: install angular cli
        run: |
          cd app
          npm install -g @angular/cli
      - name: build
        run: |
          cd app
          npm install
          ng build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SECRET_KEY}}
            known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        - name: Adding Known Hosts
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        - name: Deploy with rsync
          run:  rsync -avz app/dist/app/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html
