name: GitHub-Actions
env:
  App_Name    : "My_python"
  Package_Name: "version-${{ github.sha }}"

on: 
  push:
    branches:
    - main
jobs:
  CI:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: show path
      run : pwd && ls -lsa
    - name: Build
      run : docker build -t web_app .
    - name: azure acr
      run : docker login pythonimages.azurecr.io
      
