name: GitHub-Actions-CI
env:
  App_Name    : "My_python"
  Package_Name: "version-${{ github.sha }}"

on: 
  push:
    branches:
    - main
jobs:
  my-testing:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Git clone
      uses: actions/checkout@v1
