name: GitHub-Actions


on: 
  push:
    branches:
    - main
jobs:
  CI:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: docker build
      run: docker build . -t pythonimages/webapp:${{ github.sha }} 
      #Azure ACR(Azure Container Registry) login
    - name: Container Registery login
      run: | 
        echo ${{ secrets.GCR_TOKEN }} | docker login ghcr.io -u VardanyanG  --password-stdin 
        tr '[A-Z]' '[a-z]' | docker image tag pythonimages/webapp:${{ github.sha }}  ghcr.io/VardanyanG/pythonimages/webapp:${{ github.sha }}
        docker image push ghcr.io/VardanyanG/pythonimages/webapp:${{ github.sha }}
      

      
      

