name: GitHub-Actions
env:
  App_Name    : "My_python"
  Package_Name: "version-${{ github.sha }}"

on: 
  push:
    branches:
    - main
jobs:
  CI:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: show path
      run : pwd && ls -lsa
    - name: Build
      run : docker build -t pythonimages.azurecr.io/webapp:${{ github.sha }}  .
      #Azure ACR(Azure Container Registry) login
    - uses: azure/docker-login@v1
      with:
        login-server: pythonimages.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        run: docker push pythonimages.azurecr.io/webapp:${{ github.sha }}
      
