name: GitHub-Actions


on: 
  push:
    branches:
    - main
jobs:
  CI:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: docker build
      run: docker build . -t pythonimages.azurecr.io/webapp:${{ github.sha }} 
      #Azure ACR(Azure Container Registry) login
    - name: Azure Container Registry Login
      uses: azure/docker-login@v1
      with:
       username: ${{ secrets.ACR_USERNAME }}
       password: ${{ secrets.ACR_PASSWORD }}
       login-server: pythonimages.azurecr.io
       run: docker push pythonimages.azurecr.io/webapp:${{ github.sha }}
      
      

