name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  provisionProd:
    name: Provision Prod
    runs-on: ubuntu-latest
    environment:
      name: okopk
    steps:
    # Checkout
    - name: Checkout
      run: hello world
